# Generated by Django 5.0.1 on 2024-05-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='localtion',
            new_name='location',
        ),
    ]
